## Lab I - Dimensionality Reduction

### Workshop I

**1. Simulate any random rectangular matrix A.**

In [1]:
import numpy as np

# Set the dimensions of the matrix
n_rows = 4
n_cols = 3

# Simulate a random matrix A
A = np.random.rand(n_rows, n_cols)
print(A)

[[0.36583182 0.99678227 0.96471117]
 [0.67554354 0.34779075 0.15446184]
 [0.43235302 0.69962855 0.52119207]
 [0.56156348 0.37815309 0.70067594]]


**What is the rank and trace of A?**

In [2]:
# The rank
rank_A = np.linalg.matrix_rank(A)

# The trace (the sum of the diagonal elements of the matrix)
trace_A = np.trace(A)

print("Rank of A:", rank_A)
print("Trace of A:", trace_A)

Rank of A: 3
Trace of A: 1.2348146345391866


**What is the determinant of A?**

In [3]:
# Determinant (if possible)
if n_rows == n_cols:
    det_A = np.linalg.det(A)
    print("Determinant of A:", det_A)
else:
    det_A = None
    print("Determinant of A:", det_A)

Determinant of A: None


Calculating the determinant of a square matrix is based on a formula that involves matrix products and depends on their dimension. If a matrix is rectangular, I don't know how to apply the determinant formula directly.

**Can you invert A? How?**

Only square matrices have a defined inverse. If a rectangular matrix is not square, then it cannot have a strict inverse.

In [4]:
# Inverse of A (if possible)
if n_rows == n_cols:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:", A_inv)
else:
    A_inv = None
    print("Inverse of A:", A_inv)

Inverse of A: None


**How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?**


In [5]:
# Calculate A'A 
ATA = np.dot(A.T, A)
# Calculate AA'
AAT = np.dot(A, A.T)

# Calculate the eigenvalues and eigenvectors of A'A and AA'
eigenvalues_ATA, eigenvectors_ATA = np.linalg.eig(ATA)
eigenvalues_AAT, eigenvectors_AAT = np.linalg.eig(AAT)

# Print the results
print("Eigenvalues and eigenvectors of A'A:\n")
print("Eigenvalues:", eigenvalues_ATA, "\n")
print("Eigenvectors:", eigenvectors_ATA, "\n")

print("Eigenvalues and eigenvectors of AA':\n")
print("Eigenvalue:", eigenvalues_AAT,"\n")
print("Eigenvector:", eigenvectors_AAT, "\n")

Eigenvalues and eigenvectors of A'A:

Eigenvalues: [4.1594631  0.31152673 0.08561206] 

Eigenvectors: [[ 0.45084078  0.8896896   0.0720764 ]
 [ 0.63559163 -0.26328464 -0.72574409]
 [ 0.62671036 -0.37300618  0.68417871]] 

Eigenvalues and eigenvectors of AA':

Eigenvalue: [4.15946310e+00 3.11526731e-01 7.98602956e-17 8.56120561e-02] 

Eigenvector: [[-0.68795746 -0.53176774 -0.47743224 -0.12647553]
 [-0.30518537  0.80953916 -0.37315335 -0.33505941]
 [-0.47376718  0.01084066  0.77924685 -0.41012375]
 [-0.45729758  0.24849929  0.15996681  0.83877151]] 



The differences between the eigenvalues and eigenvectors of A'A and AA' are due to the properties of the matrices A and A' and the different ways in which the matrices are computed and manipulated to obtain the eigenvalues and eigenvectors.
* A'A is always a square matrix, and AA' is a square matrix, but this is given that A has a complete column range, since A is a rectangular matrix with fewer columns than rows, so we can assume that it is linearly independent.
* AAT is a larger matrix than ATA, so it can be more computationally expensive to calculate.
* The eigenvectors of AA' are obtained by multiplying the eigenvectors of A'A by A. This is obvious from the example, since the eigenvectors of AA' are larger.
* The eigenvalues of A'A may not contain negative values, while the eigenvalues of AA' do, these negative values may invert the direction of the variable.