## Lab I - Dimensionality Reduction

### Workshop I

**1. Simulate any random rectangular matrix A.**

In [21]:
import numpy as np

# Set the dimensions of the matrix
n_rows = 4
n_cols = 3

# Simulate a random matrix A
A = np.random.rand(n_rows, n_cols)
print(A)

[[0.77045879 0.64335567 0.87289854]
 [0.49673807 0.21626757 0.47189248]
 [0.04464037 0.99008211 0.23947806]
 [0.17852867 0.7842818  0.9720467 ]]


**What is the rank and trace of A?**

In [22]:
# The rank
rank_A = np.linalg.matrix_rank(A)

# The trace (the sum of the diagonal elements of the matrix)
trace_A = np.trace(A)

print("Rank of A:", rank_A)
print("Trace of A:", trace_A)

Rank of A: 3
Trace of A: 1.226204426996302


**What is the determinant of A?**

In [23]:
# Determinant (if possible)
if n_rows == n_cols:
    det_A = np.linalg.det(A)
    print("Determinante de A:", det_A)
else:
    det_A = None
    print("Determinante de A:", det_A)

Determinante de A: None


Calculating the determinant of a square matrix is based on a formula that involves matrix products and depends on their dimension. If a matrix is rectangular, I don't know how to apply the determinant formula directly.

**Can you invert A? How?**

Only square matrices have a defined inverse. If a rectangular matrix is not square, then it cannot have a strict inverse. 
Instead, we can use the *numpy.linalg.pinv* function to find a pseudoinverse of the matrix.
The pseudoinverse of A is used as an approximation of the inverse

In [24]:
# the pseudoinverse of A
A_pinv = np.linalg.pinv(A)
print("Pseudoinverse of A:\n", A_pinv)

Pseudoinverse of A:
 [[ 1.09346833  0.81124465  0.25104946 -1.43761406]
 [ 0.07608688 -0.11519176  1.23696358 -0.31714901]
 [-0.22487715 -0.11160135 -1.05274416  1.54423436]]


**How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?**


In [26]:
# Calculate A'A 
ATA = np.dot(A.T, A)
# Calculate AA'
AAT = np.dot(A, A.T)

# Calculate the eigenvalues and eigenvectors of A'A and AA'
eigenvalues_ATA, eigenvectors_ATA = np.linalg.eig(ATA)
eigenvalues_AAT, eigenvectors_AAT = np.linalg.eig(AAT)

# Print the results
print("Eigenvalues and eigenvectors of A'A:\n")
print("Eigenvalues:", eigenvalues_ATA, "\n")
print("Eigenvectors:", eigenvectors_ATA, "\n")

print("Eigenvalues and eigenvectors of AA':\n")
print("Eigenvalue:", eigenvalues_AAT,"\n")
print("Eigenvector:", eigenvectors_AAT, "\n")

Eigenvalues and eigenvectors of A'A:

Eigenvalues: [4.21357706 0.13928232 0.56425891] 

Eigenvectors: [[-0.37025823 -0.66921891  0.64424754]
 [-0.64809643 -0.31075578 -0.69527107]
 [-0.66549219  0.67496437  0.31865851]] 

Eigenvalues and eigenvectors of AA':

Eigenvalue: [ 4.21357706e+00  5.64258909e-01 -2.38511062e-16  1.39282320e-01] 

Eigenvector: [[ 0.62509496  0.43560767  0.5521519  -0.33857132]
 [ 0.31087074  0.42604141 -0.82134036 -0.21736632]
 [ 0.39828906 -0.7765259  -0.12730546 -0.4713456 ]
 [ 0.59496345 -0.1604438  -0.06573901  0.7848278 ]] 



The differences between the eigenvalues and eigenvectors of A'A and AA' are due to the properties of the matrices A and A' and the different ways in which the matrices are computed and manipulated to obtain the eigenvalues and eigenvectors.
* A'A is always a square matrix, and AA' is a square matrix, but this is given that A has a complete column range, since A is a rectangular matrix with fewer columns than rows, so we can assume that it is linearly independent.
* The eigenvectors of AA' are obtained by multiplying the eigenvectors of A'A by A. This is obvious from the example, since the eigenvectors of AA' are larger.
* The eigenvalues of A'A may not contain negative values, while the eigenvalues of AA' do, these negative values may invert the direction of the variable.